using System.IO;
using System.Windows;
using System.Windows.Interop;
using System.Windows.Media.Imaging;
using Clipboard = System.Windows.Clipboard;
using TextDataFormat = System.Windows.TextDataFormat;

namespace ClipHive;

/// <summary>
/// Monitors clipboard changes via Win32 <c>AddClipboardFormatListener</c>.
/// Fires <see cref="ClipboardChanged"/> for new Unicode text and
/// <see cref="ClipboardImageChanged"/> for new images/screenshots,
/// skipping changes generated by <see cref="IPasteService"/> to prevent re-entry.
/// </summary>
public sealed class ClipboardMonitorService : IClipboardMonitorService
{
    private readonly IPasteService _pasteService;

    private HwndSource? _hwndSource;
    private bool _listening;
    private bool _disposed;

    public event EventHandler<string>?  ClipboardChanged;
    public event EventHandler<byte[]>?  ClipboardImageChanged;

    public ClipboardMonitorService(IPasteService pasteService)
    {
        ArgumentNullException.ThrowIfNull(pasteService);
        _pasteService = pasteService;
    }

    public void Start()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        if (_listening) return;

        var parameters = new HwndSourceParameters("ClipHive-ClipboardMonitor")
        {
            Width  = 0,
            Height = 0,
            WindowStyle         = 0,
            ExtendedWindowStyle = 0x00000080,
            ParentWindow        = IntPtr.Zero,
        };

        _hwndSource = new HwndSource(parameters);
        _hwndSource.AddHook(WndProc);
        Win32.AddClipboardFormatListener(_hwndSource.Handle);
        _listening = true;
    }

    public void Stop()
    {
        if (!_listening || _hwndSource is null) return;

        Win32.RemoveClipboardFormatListener(_hwndSource.Handle);
        _hwndSource.RemoveHook(WndProc);
        _listening = false;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        Stop();
        _hwndSource?.Dispose();
        _hwndSource = null;
    }

    // ── Window procedure ───────────────────────────────────────────────────────

    private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
    {
        if (msg == Win32.WM_CLIPBOARDUPDATE)
        {
            handled = true;
            OnClipboardUpdate();
        }
        return IntPtr.Zero;
    }

    private const int MaxContentChars = 100_000;

    private void OnClipboardUpdate()
    {
        if (_pasteService.IsPasting) return;

        // Images / screenshots take priority
        if (Clipboard.ContainsImage())
        {
            TryGetClipboardImageWithRetry();
            return;
        }

        if (Clipboard.ContainsText(TextDataFormat.UnicodeText))
            TryGetClipboardTextWithRetry();
    }

    // ── Text retry ─────────────────────────────────────────────────────────────

    private void TryGetClipboardTextWithRetry()
    {
        string? text = null;
        try
        {
            text = Clipboard.GetText(TextDataFormat.UnicodeText);
        }
        catch (Exception)
        {
            var retryTimer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromMilliseconds(50) };
            retryTimer.Tick += (_, _) =>
            {
                retryTimer.Stop();
                try
                {
                    string? t = Clipboard.GetText(TextDataFormat.UnicodeText);
                    if (!string.IsNullOrEmpty(t) && t.Length <= MaxContentChars)
                        ClipboardChanged?.Invoke(this, t);
                }
                catch (Exception) { /* give up */ }
            };
            retryTimer.Start();
            return;
        }

        if (!string.IsNullOrEmpty(text) && text.Length <= MaxContentChars)
            ClipboardChanged?.Invoke(this, text);
    }

    // ── Image retry ────────────────────────────────────────────────────────────

    private void TryGetClipboardImageWithRetry()
    {
        try
        {
            var imageBytes = GetClipboardImageBytes();
            if (imageBytes != null)
                ClipboardImageChanged?.Invoke(this, imageBytes);
        }
        catch (Exception)
        {
            var retryTimer = new System.Windows.Threading.DispatcherTimer { Interval = TimeSpan.FromMilliseconds(50) };
            retryTimer.Tick += (_, _) =>
            {
                retryTimer.Stop();
                try
                {
                    var bytes = GetClipboardImageBytes();
                    if (bytes != null)
                        ClipboardImageChanged?.Invoke(this, bytes);
                }
                catch (Exception) { /* give up */ }
            };
            retryTimer.Start();
        }
    }

    /// <summary>
    /// Reads the current clipboard image and encodes it as JPEG bytes.
    /// Returns null if the clipboard contains no image or the image is too large.
    /// </summary>
    private static byte[]? GetClipboardImageBytes()
    {
        var bitmapSource = Clipboard.GetImage();
        if (bitmapSource is null) return null;

        // Scale down if very large (max 1920 wide to keep storage manageable)
        const int MaxWidth = 1920;
        BitmapSource source = bitmapSource;
        if (source.PixelWidth > MaxWidth)
        {
            double scale = (double)MaxWidth / source.PixelWidth;
            source = new TransformedBitmap(source, new System.Windows.Media.ScaleTransform(scale, scale));
        }

        using var ms = new MemoryStream();
        var encoder = new JpegBitmapEncoder { QualityLevel = 85 };
        encoder.Frames.Add(BitmapFrame.Create(source));
        encoder.Save(ms);

        byte[] bytes = ms.ToArray();

        // Skip if > 5 MB
        const int MaxImageBytes = 5 * 1024 * 1024;
        return bytes.Length > MaxImageBytes ? null : bytes;
    }
}
